SHIP-0007: Release Shipwright CLI through Package Managers
shipwright-io/community pull request #16
Opened 2021-07-07 09:45 UTC by HeavyWombat

_TL;DR_: 
> Users of CLI tools are accustomed to the usage of package managers to install a tool and to keep it up-to-date. The `shp` CLI tool should have an option to be installed with such a package manager.

2021-07-07 09:48 UTC, HeavyWombat commented
It would also solve https://github.com/shipwright-io/cli/issues/23.

2021-07-07 10:22 UTC, qu1queee requested changes
SHIP looks good to me, this is needed for CLI. I just have a minor request for change.

2021-07-07 10:22 UTC, qu1queee commented on ships/0007-package-manager-releases.md
> +see-also:
can u remove this sections, same for the "replaces" and the "superseded-by"

2021-07-09 10:59 UTC, qu1queee approved these changes
thanks, approving, leaving the lgtm for someone in RH

/approve

2021-07-13 06:06 UTC, otaviof commented
Thanks putting it together, @HeavyWombat!

/lgtm

2021-07-13 06:06 UTC, otaviof approved these changes

2021-07-13 06:06 UTC, merged