SHIP-0029: One-Off Builds
shipwright-io/community pull request #64
Opened 2022-02-24 12:31 UTC by dalbar

Adds an enhancement proposal to include one-off builds.

2022-02-24 12:31 UTC, dalbar commented
/assign @qu1queee

2022-02-27 20:04 UTC, SaschaSchwarze0 requested changes
Looking forward to the next version with implementation details. :-)

2022-02-27 20:04 UTC, SaschaSchwarze0 commented on ships/0029-one-off-builds.md
> +Additionally, we require that `buildSpec` is never used in conjunction with any of `buildRef`, `output`,
To complete your list: paramValues, env, timeout.

I think it makes sense to generalize the statement like this: `buildSpec` is not meant to be used in conjunction `buildRef` and with any other field inside the BuildRun spec which is meant to override behavior of a Build. These are today: `env`, `output`, `paramValues`, `sources`, and `timeout`. Other fields such as `serviceAccount` are allowed in conjunction with `buildSpec`.

2022-02-27 20:04 UTC, SaschaSchwarze0 commented on ships/0029-one-off-builds.md
> +well documented. Besides, this proposal only adds a new workflow for certain cases. The `spec.build.spec` is optional and a
```suggestion
well documented. Besides, this proposal only adds a new workflow for certain cases. The `spec.buildSpec` is optional and a
```

2022-02-28 08:30 UTC, SaschaSchwarze0 approved these changes
/approve

2022-03-01 11:07 UTC, qu1queee requested changes
@dalbar this is nice written. I have just a comment on the reviewers/approvers. 

Can we extend the `### Implementation Notes` part?

2022-03-01 12:26 UTC, dalbar commented on ships/0029-one-off-builds.md
> +  - TBD
done thanks

2022-03-01 12:27 UTC, dalbar commented on ships/0029-one-off-builds.md
> +  - TBD
done thanks

2022-03-02 18:08 UTC, adambkaplan approved these changes
/lgtm

Approving this as provisional, though truthfully I would consider this "implementable".

With this and other proposals, we are increasing the number of validations that are being done against spec fields. This can lead to a bad user experience when a lot of "gotchas" can be caught at object admission (rather than during reconciliation).

@imjasonh proposed adding a validating admission webhook in https://github.com/shipwright-io/build/issues/596 - I think it is time we codify this in a SHIP.

2022-03-02 18:08 UTC, adambkaplan commented on ships/0029-one-off-builds.md
> +    BuildRef BuildRef `json:"buildRef,omitempty"`
Side note - technically this is not a breaking change. Moving a field from required to optional will not impact existing `BuildRun` objects.

2022-03-02 18:08 UTC, adambkaplan commented on ships/0029-one-off-builds.md
> +actual cluster resource. After that point, both branches merge in the current workflow that eventually ends up in a
+1

2022-03-02 18:10 UTC, merged