Ship that introduces per namespace mirror registries
shipwright-io/community pull request #76
Opened 2022-04-06 11:17 UTC by ricardomaraschini

2022-04-22 19:00 UTC, SaschaSchwarze0 requested changes
Very valuable @ricardomaraschini. I assume that the global registry mirror will then be optional? This is worth mentioning as this is I think a requirement for multi-tenant systems. As a consequence, if there is no global registry mirror and there is also a namespace without a namespace-specific mirror, then all image-related requests in that namespace will fail.

2022-04-22 19:00 UTC, SaschaSchwarze0 commented on ships/0032-image-read-mirror-from-namespace.md
> +This enhancement proposal suggests the introduction a per namespace mirror registry configuration,
```suggestion
This enhancement proposal suggests the introduction of a per namespace mirror registry configuration,
```

2022-04-22 19:00 UTC, SaschaSchwarze0 commented on ships/0032-image-read-mirror-from-namespace.md
> +it can containg the following properties:
```suggestion
it can contain the following properties:
```

2022-04-25 07:27 UTC, ricardomaraschini commented
> Very valuable @ricardomaraschini. I assume that the global registry mirror will then be optional? This is worth mentioning as this is I think a requirement for multi-tenant systems. As a consequence, if there is no global registry mirror and there is also a namespace without a namespace-specific mirror, then all image-related requests in that namespace will fail.

I added a couple of notes on this regard [here](https://github.com/shipwright-io/community/pull/76/commits/e791b047b45751ae5d186bcbc63990e7f8488472). PTAL.

2022-04-25 07:33 UTC, SaschaSchwarze0 approved these changes
/approve

2022-05-03 07:28 UTC, ricardomaraschini commented
@otaviof @SaschaSchwarze0 Do I need another approval here ?

2022-05-03 11:53 UTC, SaschaSchwarze0 commented
> @otaviof @SaschaSchwarze0 Do I need another approval here ?

We do not have a guideline, but so far never merged a SHIP with just a single review. You can bring it up in a community meeting that you are looking for a review.

2022-05-23 13:02 UTC, otaviof commented
/lgtm

2022-05-23 13:03 UTC, merged