SHIP-0003: Tekton Custom Task
shipwright-io/community pull request #9
Opened 2021-06-03 13:59 UTC by imjasonh

cc @sbose78 @adambkaplan @qu1queee

2021-06-03 16:03 UTC, adambkaplan approved these changes
/approve

This is a good provisional proposal. My comments are meant for general discussion or items to consider when we get to the implementable phase.

2021-06-03 16:03 UTC, adambkaplan commented on ships/0003-tekton-custom-task.md
> +A Tekton `PipelineRun` executes a `Run` that tells Shipwright to create a `BuildRun`, which executes by creating a Tekton `TaskRun` under the hood.
This is good to note for console implementations that want to visualize Shipwright builds. Consoles will always see a BuildRun mirror a TaskRun, so perhaps this isn't a huge issue?

2021-06-03 16:21 UTC, imjasonh commented on ships/0003-tekton-custom-task.md
> +Currently, Tekton Custom Task `Run` resources have the `v1alpha1` API version.
Good call, noted in the doc.

2021-06-03 16:21 UTC, imjasonh commented on ships/0003-tekton-custom-task.md
> +Because Shipwright already necessarily requires Tekton to be installed, this change should not incur any additional dependencies on users or operators.
v0.19.0 added initial support, so it shouldn't impose any more onerous Tekton version requirements than we already impose today. Noted in the doc.

2021-06-03 16:22 UTC, imjasonh commented on ships/0003-tekton-custom-task.md
> +As a result, a bug or exploit of the Shipwright controller could lead to unexpected or malicious behavior in the user's cluster.
Yeah, it's unfortunately pretty unavoidable. I believe this is called out in Tekton's Custom Task EP as well.

2021-06-03 16:22 UTC, imjasonh commented on ships/0003-tekton-custom-task.md
> +A Tekton `PipelineRun` executes a `Run` that tells Shipwright to create a `BuildRun`, which executes by creating a Tekton `TaskRun` under the hood.
Good call, noted.

2021-06-07 13:28 UTC, sbose78 approved these changes
Looks good, would be nice to have a sample tekton pipeline yaml included in the proposal. :)

2021-06-07 13:28 UTC, sbose78 commented on ships/0003-tekton-custom-task.md
> +   The Custom Task is necessary here because Tekton Triggers is only designed to create Tekton resources, and not arbitrary non-Tekton resources such as a `BuildRun`.
+1

2021-06-07 13:28 UTC, sbose78 commented on ships/0003-tekton-custom-task.md
> +   This would enable them to, for example, run unit tests before calling Shipwright to build a container image, or to test, scan or deploy an image produced by Shipwright.
+1

2021-06-07 13:28 UTC, sbose78 commented on ships/0003-tekton-custom-task.md
> +As a result, a bug or exploit of the Shipwright controller could lead to unexpected or malicious behavior in the user's cluster.
Yeah, good to have this noted down.

2021-06-07 13:45 UTC, SaschaSchwarze0 reviewed
I would like to make sure we make this feature meet the user's use cases. So, from a user's perspective, one might be missing certain features to integrate a Run which is a BuildRun into a larger Tekton pipeline:

* passing the source through a Tekton workspace; or at least overwriting the source (like the revision) of the build through the Pipeline
* getting insights into the image that was built (the image sha or the full image URL)

All these things require features in the build controller, but for the e2e story = to build a reasonable Tekton pipeline that does something useful, I think it will be necessary to speak out these things already.

2021-06-22 20:38 UTC, qu1queee commented
@imjasonh sorry for the late reply in here. I would like this SHP to consider more aspects around the integration for:

- Tekton Triggers
- An embedded SHP in Tekton Pipeline resources

I do not have the whole picture yet clear, but I wrote some key points we might wanna consider, see [delta](https://github.com/imjasonh/community-2/compare/tekton-custom-task...qu1queee:qu1queee/shp003-feedback?expand=1&short_path=8e9ca89#diff-8e9ca89d5011659400100d5a71cf5e4cd22c03dc80353820f599d53b21792adf). I can open a proper PR to yours if you want, or you can consume some of the ideas I wrote there. Let me know.

2021-06-22 20:39 UTC, qu1queee requested changes
@imjasonh sorry for the late reply in here. I would like this SHP to consider more aspects around the integration for:

- Tekton Triggers
- An embedded SHP in Tekton Pipeline resources

I do not have the whole picture yet clear, but I wrote some key points we might wanna consider, see [delta](https://github.com/imjasonh/community-2/compare/tekton-custom-task...qu1queee:qu1queee/shp003-feedback?expand=1&short_path=8e9ca89#diff-8e9ca89d5011659400100d5a71cf5e4cd22c03dc80353820f599d53b21792adf). I can open a proper PR to yours if you want, or you can consume some of the ideas I wrote there. Let me know.

2021-07-15 16:37 UTC, imjasonh commented
Hi @qu1queee @SaschaSchwarze0 sorry for the _very_ late reply. 😓 

I agree there's probably more design work to be done to think through how this integrates with a Tekton Pipeline, especially the areas you've highlighted around reusing Tekton's `workspaces`, and emitting `results` to downstream Tasks. I believe with changes like #13 we can have the Custom Task controller adapt Shipwright Build `.status.results` (incl git SHA and image SHA) to Tekton `.status.results`, and with the evolving work around `sources` we can find some way to adapt `workspaces` to an input `source`.

Ultimately this is a `provisional` SHIP, so I don't think we need to answer all of these questions definitively before merging it. We can layer on more design considerations and features before it becomes `implementable`.

2021-07-23 19:54 UTC, adambkaplan commented
@imjasonh since we merged the previous enhancement proposals here, please update the title and numbering to SHIP-0020

2021-08-01 16:57 UTC, qu1queee commented
@imjasonh moving out of this PR as I would not be able to provide feedback in the next weeks. @SaschaSchwarze0 fyi.

2022-06-20 13:06 UTC, closed without merging